<?php


function mixnyc_custom_form_alter(&$form, $form_state, $form_id) {

  //see this comment: http://drupal.org/node/1437430#comment-6848846
  if ($form_id == 'uc_cart_view_form') {
    $form['#submit'][] = 'mixnyc_remove_callback';
  }

  if ($form['#node_edit_form']) {
    global $user;
    $roles = $user->roles;
    //SUPPRESS THE TEXT AREA FOR REVISION INFO FOR REGULAR USERS
    if ($roles && (count($roles) == 1) && 
        in_array('authenticated user', $roles)) {

      $form['revision_information']['#access'] = FALSE;  
    }

    if (isset($node->field_aspect_ratio)) {
      //
    }
  }

  if ($form_id == 'film_submission_node_form') {
    global $user;

    $nid = $form['nid']['#value'] ? $form['nid']['#value'] : 0;

    $paid_count = mixnyc_custom_get_film_count($user->uid, 0, 'paid');
    $all_count = mixnyc_custom_get_film_count($user->uid, 0, 'all');	

    if (!$nid && !$paid_count && $all_count) {
      drupal_set_message(
        t("Sorry, you must complete the checkout/payment process for your 
           first Film Submission before you can begin another. Once you 
           submit and go through the checkout proces withyour first film
           all your subsequent submissions will be free."), 'error'); 
      drupal_goto('forms');
    }
  }
}

function mixnyc_remove_callback ($form, &$form_state){

  if (substr($form_state['triggering_element']['#name'], 0, 7) == 'remove-') {
  
   $remove_num = substr($form_state['triggering_element']['#name'], 7);
   $cart_item_id  = $form_state['values']['items'][$remove_num]['cart_item_id'];
   $item_pre = $form_state['build_info']['args'][0][$cart_item_id];

    if (variable_get('uc_node_checkout_delete_nodes', TRUE)) {
      if (isset($item_pre->data['node_checkout_nid'])) {
         node_delete($item_pre->data['node_checkout_nid']);
       }
     } 
   } 
} 


/**
 * Implements hook_menu().
 */
/**
function mixnyc_custom_menu() {
  $items = array();
  // we have to create the 'Devel settings' menu item ourselves
  $items['home'] = array(
    'page callback'    => 'mixnyc_custom_home_controller',
    'page arguments' => array(1),
    'access callback' => TRUE,
  );
  return $items;
}
*/

function mixnyc_custom_home_controller() {
  global $user;
  if ($user->uid) {
    drupal_goto('forms');
  }
  else  {
    drupal_goto('user', array('query'=>array('destination'=>'forms')));
  }
}

function mixnyc_custom_submission_view_message(&$node, &$site, $view_mode) {
  $view_mode = ($view_mode == 'full') ? TRUE : FALSE;

  return 
    mixnyc_custom_updated_submission_status_message($node, $site, $view_mode);
}
function mixnyc_custom_updated_submission_status_message(&$node, &$site,
                                                         $view_mode=FALSE){
  
  $view = views_get_view('submission_status_message');
  $view->set_display('status_message_block');
  $view->set_arguments(array($node->nid));
  $view->build('status_message_block');
  $view->execute('status_message_block');
  $node_order = $view->result[0];

  $type = ucwords(str_replace('_', ' ', $node->type));
  
  $submission_type_requires_payment = isset($node->field_requires_payment) ?
    TRUE : FALSE;

  $order_status = 
   $node_order->uc_order_products_uc_node_checkout_order_products__uc_orders;
  
  $order_id = 
   $node_order->uc_order_products_uc_node_checkout_order_products__uc_orders_1;

  $amount_paid = 
   $node_order->uc_order_products_uc_node_checkout_order_products__uc_orders_2;

  $payment_type = 
   $node_order->uc_order_products_uc_node_checkout_order_products__uc_orders_3;

  $product_count = 
   $node_order->uc_order_products_uc_node_checkout_order_products__uc_orders_4;

  $product_cost = 
    $node_order->uc_order_products_uc_node_checkout_order_products_price;

  $film_gauges = isset($node->field_film_gauge) ? 
    count($node->field_film_gauge['und']) : 0;

  $checklist_completed = isset($node->field_checklist_completed) ?
    $node->field_checklist_completed['und'][0]['value'] : FALSE;

  $checklist_completed = ($checklist_completed == 'YES') ? TRUE : FALSE;

  $view_order_link = 
    l(t("View Payment"), "user/".$node->uid."/orders/".$order_id);

  $make_payment_link = l("Payment", "cart");

  $film_count = mixnyc_custom_get_film_count($node->uid, $node->nid, 'paid');
  $has_more_than_one_film = ($film_count > 0) ? TRUE : FALSE;
  
  $admin_paid = isset($node->field_admin_paid) ?
    $node->field_admin_paid['und'][0]['value'] : FALSE;

  $admin_paid_amount = isset($node->field_admin_paid_amount) ?
    $node->field_admin_paid_amount['und'][0]['value'] : FALSE;
  
/**
  dsm($type,'type');
  dsm($submission_type_requires_payment,'requires payment');
  dsm($order_id,'order_id');
  dsm($product_count,'product_count');
  dsm($amount_paid,'amount_paid');  
  dsm($product_cost,'product_cost');  
  dsm($view_order_link,'view_order_link');
  dsm($make_payment_link,'payment_link');
  dsm($film_gauges, 'film gauges');
  dsm($film_count, 'film_count');
  dsm($has_more_than_one_film, 'more than 1 film?');
  dsm($order_status, 'order status');
  dsm($payment_type, 'payent type');
  dsm($checklist_completed, 'checklist_completed');
  dsm($view);
  dsm($node);
  dsm($node_order);
  dsm($admin_paid);
  dsm($admin_paid_amount);
 */


  $ret = "";

  //FIXME, FIGURE OUT HOW TO PUT INTO t() function with <i>
  if (!$view_mode) {
    $ret .= "<h2>Your $type: <i>".$node->title.
      "</i> has been succussfully saved.</h2>";
  }
  else {
    $ret .= "<h2>$type: ".$node->title."</h2>";
  }

  $ret .= "<ul>";
  if (!$checklist_completed) {
    $ret .= "<li><strong>".t("Status: Rough Draft")."</strong><br/>";
    $ret .= 
      "Please take note, your $type has NOT been submitted to the 
       MIX NYC team. That will not happen until you complete the Checklist
       for your $type. The Checklist is at the bottom of your ".
       l("$type edit page", "node/".$node->nid."/edit", 
         array('query'=>array('destination'=>'forms'))).
       ".<br/><br/></li>";
  }
  else {
    $ret .= "<li><strong>".t("Status: Completed")."</strong><br/>";
    $ret .= 
      "Please take note, your $type has been submitted to the MIX NYC team for
       approval. You are no longer able to make changes to your $type. If you 
       discover incorrect information please let us know via our ".
       l(t("Contact Form"), "contact").".<br/><br/>";
       
    if ($type == "Film Submission") {
      $ret .=
        "Please send your preview DVD and/or any supplemental materials to: 
	<br/>
         MIX NYC<br/>
	 ATTN: 2013 Entries<br/>
         82 Nassau St. PMB 341<br/>
         New York, NY 10038<br/><br/></li>"; 
    }
  }

  //////////////////////////////////////////////////////////////////////////
  //PAYMENT
  if ($admin_paid) {
     $ret .="<li><strong>".t("Payment Status: Successful")."</strong><br/>";
    $ret .= 
      t("A MIX NYC volunteer has successfully registered your payment</li>"); 
  }
  else if ($checklist_completed && $submission_type_requires_payment && 
      $payment_type=='check' && strtolower($order_status)=='pending') {
    $ret .="<li><strong>".t("Payment Status: Awaiting Check")."</strong><br/>";
    $ret .= 
      t("We have not yet processed your check. We may have already received 
      your check in the mail but have not yet updated our database.").
      "<br/>$view_order_link</li>"; 
  }
  else if ($checklist_completed && $submission_type_requires_payment && 
           $order_id && ($amount_paid == 0) ) {
    $ret .="<li><strong>".t("Payment Status: N/A")."</strong><br/>";
    $ret .=
      t("You were not charged for your submission.")."<br/> ".
      $view_order_link."</li>";
  }
  //
  else if ($checklist_completed && $submission_type_requires_payment && 
            $payment_type=='check') {
    $ret .="<li><strong>".t("Payment Status: Check Received")."</strong><br/>";
    $ret .=
      t("We have successfully received and processed your check.")."<br/> ".
      $view_order_link;
  }
  //
  else if ($submission_type_requires_payment && $order_id) {
    $ret .="<li><strong>".t("Payment Status: Successful")."</strong><br/>";
    $ret .=
      t("We have successfully processed your payment.")."<br/>".
      $view_order_link;
  }
  //
  else if ($checklist_completed && $submission_type_requires_payment && 
            $has_more_than_one_film) {
    $ret .="<li><strong>".t("Payment Status: Awaiting Payment").
      "</strong><br/>";
    $ret .=
      "Please make your $make_payment_link. If you have already submitted a 
       film, all subsequent film submissions are free if you use this discount
       code:<br/>
       <i>mixnyc2film</i></li>";
  }
  //
  else if ($checklist_completed && $submission_type_requires_payment && 
            $film_gauges) {
    $ret .="<li><strong>".t("Payment Status: Awaiting Payment").
      "</strong><br/>";
    $ret .=
      "Please make your $make_payment_link. If your $type is actually
       being submitted on 35mm, 16mm, 8mm, or Super8 you will not have to 
       make a payment when you checkout if you use this 
       discount code:<br/><i>mixnyc2film</i></li>";
  }
  else if ($checklist_completed && $submission_type_requires_payment){
    $ret .="<li><strong>".t("Payment Status: Awaiting Payment").
      "</strong><br/>";
    $ret .=
      "Please make your ".$make_payment_link.
      " before submitting any more work. Once payment is made, you will be 
      given a discount code after your next submission. If you are planning 
      on sending a check or money order from a non U.S. country please be 
      prepared to add a $5 processing fee. </li>";
  }
  else if ($submission_type_requires_payment){
    $ret .="<li><strong>".t("Payment Status: Awaiting Form Completion").
      "</strong><br/>";
    $ret .=
      "When you have completed your $type and submitted it to MIX NYC for
       approval you will be asked to make your payment.</li>";
  }

  $ret .= 
    "<br/><br/><li>If you have any feedback/problems/suggestions about our 
     online submission process please use our ".
     l(t("Contact Form"), "contact");
  $ret .= "<br/></ul><br/>";
  return $ret;
}

function mixnyc_custom_get_film_count($uid, $nid, $mode = 'paid') {
  $sql =  "
    SELECT count(*) as number
    FROM {node} sub
    LEFT JOIN {uc_node_checkout_order_products} n_check
      ON sub.nid = n_check.nid
    LEFT JOIN {uc_order_products} prods 
      ON n_check.order_product_id = prods.order_product_id
    LEFT JOIN {uc_orders} ord 
      ON ord.order_id = prods.order_id
    LEFT JOIN {field_data_field_checklist_completed} comp
      ON sub.vid=comp.revision_id
    LEFT JOIN {field_data_field_admin_paid} admin_paid
      ON sub.vid=admin_paid.revision_id
    WHERE status=1 
    AND sub.uid=$uid 
    AND sub.nid!=$nid
    AND type='film_submission'
  ";

  if($mode != 'all') {
    $sql .= "
      AND comp.field_checklist_completed_value = 'YES'
      AND 
        ((LOWER(ord.order_status) !='pending'
          AND LOWER(ord.order_status) !='abandoned'
          AND LOWER(ord.order_status) !='canceled')
         OR
         (admin_paid.field_admin_paid_value=1))
    ";
  }
  
  $results = db_query($sql);
  $film_count = $results->fetchObject()->number;
  return $film_count;
}

function mixnyc_custom_checklist_fields() {
  return array(
    'field_documentation_check' => 'Documentation?',
    'field_stills_check' => 'Image/Stills?',
    'field_dvd_vhs_check' => 'DVD?',
  );
}
function computed_field_field_checklist_completed_compute(&$entity_field, $entity_type, $entity, $field, $instance, $langcode, $items) {

  $fields = mixnyc_custom_checklist_fields();
  

  $unchecked_checklist_item_count = 0;
  foreach($fields as $name=>$label) {
    if (isset($entity->{$name})) {
      $unchecked_checklist_item_count++;
      if(count($entity->{$name}['und'])) {
        $unchecked_checklist_item_count--;
      }
    }
  }

  if ($unchecked_checklist_item_count){
    $cmptd_value = NULL; 
  }
  else {
    $cmptd_value = "YES";
  }

  $entity_field[0]['value']= $cmptd_value;

}
